# Site settings
title: Mang-la-Desh!
email: info@mangladesh.com
description: > # this means to ignore newlines until "baseurl:"
  Wear Mang-la-Desh! Swim and Lounge Apparel and be in an excited state of mind always propelling forward with a never-ending passion for life!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.mangladesh.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
